### ISSUE TITLE
some pdf file open failed.

### ISSUE THREAD

**Issue by oevery** [yermolim/ts-pdf#4]
some pdf file open failed.this is the error screenshot:
![image](https://user-images.githubusercontent.com/26798347/157821596-198772cc-bd6e-46c2-87ba-8b2c6fd529d8.png)
example pdf file:
[Mobile_App_UX_Principles.pdf](https://github.com/yermolim/ts-pdf/files/8229957/Mobile_App_UX_Principles.pdf)
Please tell me how to fix this error, thanks a lot bro.

**Comment by LibertyNLP** [comment]
Hi , I wish my work can help you.
I have figured out a solution of pdf.js annotation, use only pdf.js dist, and it is very easy to import into your project.

Demo and source code: https://demos.libertynlp.com/#/pdfjs-annotation
Demo video:https://www.youtube.com/watch?v=IYD7WKzx-yc&t=3s

functions:
① highlight : highlight selected text;
② underline : underline selected text;
③ edit: edit annotation ( copy/delete/add comment/navigate );
④ output annotations : output annotations for importing;
⑤ import annotations : import annotations for current file;
⑥ download annotations : download annotations and comments text;
⑦ undo annotations : undo annotations in current page;
⑧ help : open help file;

**Comment by yermolim** [comment]
@oevery 
_I'm sorry. It took so long for me to answer because of my personal problems (I've lost my home because of the war in my country, I'm forbidden to cross the border, and I'm still trying to get out of the depression). I understand that for you it is no longer relevant. Obviously, you either switched to another solution or found the fix yourself. But still..._

The problem was happening because the attached file is a linearized PDF file (such files are described in Annex F to the PDF specification). And the files of this type lack some properties required in regular PDF files. 

I've removed one of the checks forbidding the opening of such files, and it seems to work now with the latest version. Maybe it'll be useful for someone else.

But be aware that if you save the file using the module, it'll no more be a linearized one. I don't know the scenarios where it could harm (it should only affect the file opening speed), but it'd be good to implement the proper support for linearized files. I added this to TODOs, but I don't know when I'll be ready to do that.
