### ISSUE TITLE
In the iOS app, the annotation is upside-down and mirrored. 

### ISSUE THREAD

**Issue by iruthaya** [yermolim/ts-pdf#8]
First, many thanks for your excellent effort. 

Please watch the video below and assist me in solving this difficulty as I'm trying to integrate this into an iOS app (run this via the iPhone 11 simulator).

https://user-images.githubusercontent.com/20356990/208036554-32375fdf-11cb-4368-aa87-437e15bd4b3e.mov

**Comment by yermolim** [comment]
Hi! Sorry for the delay in response. 
The code within the app sets a simple matrix as a value of the SVG transform attribute to transform the newly created annotation from the PDF coordinate space to the HTML one (mirroring it vertically). And from the provided video, it looks like it's not supported or produces an incorrect result in iOS because when I comment out the corresponding lines I get similar results in a Windows browser to what is shown in your video. Maybe some alternative ways to transform SVG elements can be used or some polyfills. But it's just a hint for you where to start from. I don't own any Apple devices and I usually develop for Windows or Android, so I'm not aware of such nuances.

<img width="542" alt="image" src="https://user-images.githubusercontent.com/39064665/208629805-9e45339b-a0fc-4901-ab1c-216b41a35cd2.png">

I'll try to look at it when I have a possibility. Unfortunately, I've been having issues with the electricity and internet connection lately because of the war in my country, so I can't tell you how soon I can do that.

**Comment by iruthaya** [comment]
Thank you for your reply. Hope everything gets better in your country soon. I will try what you advised me

**Comment by iruthaya** [comment]
This problem has been resolved; setAttribute("style", "transform: 'value'; -webkit-transform: 'value';) has been used in instead of setAttribute("transform", "value") wherever that was used. 

Thank you for the guidance.

**Comment by Niki2k1** [comment]
@iruthaya have you planned to create a pr to include the fixes in this repo?

**Comment by iruthaya** [comment]
@Niki2k1 I believe this problem has been resolved by @yermolim. Please have a look at this.
https://github.com/yermolim/ts-pdf/commit/c86b903a2f4ac31398b518b71a4580131dd77366

**Comment by Niki2k1** [comment]
Ah yeah I see. Thank you for answering. The Inputs are in correct orientation now. But as soon as you hit the checkmark button to finish the annotation its added in the wrong orientation again.

**Comment by iruthaya** [comment]
Hi @Niki2k1, Please record the error and share it here.

**Comment by iruthaya** [comment]
Hi @yermolim, I am aware that you do not own an Apple device, so you are unable to verify that. kindly look on my chances as follow. 

**appearance-stream-renderer.ts**
path.setAttribute("transform", `matrix(${this.state.matrix.toFloatShortArray().join(" ")})`);
into 
path.setAttribute("style", `transform : matrix(${this.state.matrix.toFloatShortArray().join(", ")}); -webkit-transform: : matrix(${this.state.matrix.toFloatShortArray().join(", ")});`);

**annotation-dict.ts**
this._svgContentCopy.setAttribute("transform", "matrix(1 0 0 1 0 0)");
into 
this._svgContentCopy.setAttribute("style", "transform : matrix(1, 0, 0, 1, 0, 0); -webkit-transform : matrix(1, 0, 0, 1, 0, 0);");

elementContainer.setAttribute("transform", "scale(1, -1)");
into
elementContainer.setAttribute("style", "transform : scale(1, -1); -webkit-transform: scale(1, -1);");

**page-annotation-view.ts**
this._svg.setAttribute("transform", "scale(1, -1)");
into
this._svg.setAttribute("style", "transform : scale(1, -1); -webkit-transform: scale(1, -1);");

**annotator.ts**
svg.setAttribute("transform", "matrix(1 0 0 -1 0 0)");
into
svg.setAttribute("style", "transform : matrix(1, 0, 0, -1, 0, 0); -webkit-transform : matrix(1, 0, 0, -1, 0, 0);");
